name: linux build 

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Prepare environment
      run: |
        sudo mkdir -p /build
        sudo chown $USER:$USER /build
        mkdir -p /build/buildroot
        mkdir -p /build/lib
        curl -L https://github.nzbget.com/buildroot-aarch64.tar.gz -o /build/buildroot/buildroot.tar.gz
        curl -L https://github.nzbget.com/libs-aarch64.tar.gz -o /build/lib/libs.tar.gz
        tar zxf /build/buildroot/buildroot.tar.gz -C /build/buildroot
        tar zxf /build/lib/libs.tar.gz -C /build/lib
        sudo apt-get install -y autoconf automake bc build-essential cmake cpio curl file git libtool pkg-config rsync unzip wget libtinfo5

    - name: Build
      run: |
        BUILD_PARAMS="linux bin installer"
        if [ "$GITHUB_REF_NAME" == "develop" ] || [ "$GITHUB_REF_NAME" == "main" ]; then
          BUILD_PARAMS="$BUILD_PARAMS debug release"
        else
          BUILD_PARAMS="$BUILD_PARAMS release"
        fi
        if [ "$GITHUB_REF_NAME" != "main" ]; then
          BUILD_PARAMS="$BUILD_PARAMS testing"
        fi
        bash linux/build-nzbget.sh bin aarch64

    # - name: Rename build artifacts
    #   if: github.ref_name != 'main' && github.ref_name != 'develop'
    #   run: |
    #     cd build
    #     SUFFIX="-${GITHUB_REF_NAME/\//-}-bin-linux.run"
    #     for FILE in *.run; do
    #       [ -f $FILE ] || continue
    #       NEW_FILE=${FILE/-bin-linux.run/$SUFFIX}
    #       mv $FILE $NEW_FILE
    #     done

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nzbget-linux-installers
        path: build/*.tar.gz
        retention-days: 5
