name: windows tests

on:
  push:
    branches:
    - develop
    - main
    - feature/*
  pull_request:
    branches:
    - develop
    - main
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2022

    steps:

    - name: Prepare environment
      uses: johnwason/vcpkg-action@v6
      id: vcpkg
      with:
        pkgs: openssl libxml2 zlib boost-json boost-asio boost-test
        triplet: x64-windows-static
        token: ${{ github.token }}
        github-binarycache: true

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        cmake --version
        mkdir build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DBUILD_ONLY_TESTS=ON
        cmake --build . --config Release -j 4

    - name: Test
      run: |
        cd build
        ctest -C Release

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: nzbget-windows-test-log
        path: build/Testing/Temporary/LastTest.log
        retention-days: 5
