name: windows tests 

on:
  push:
    branches:
    - develop
    - main
    - feature/*
  pull_request:
    branches:
    - develop
    - main
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2019

    steps:

    - name: Setup build environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |        
        cmake --version
        mkdir build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DBUILD_ONLY_TESTS=ON
        cmake --build . --config Release -j 2

    - name: Test
      run: |
        cd build
        ctest -C Release

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: nzbget-windows-test-log
        path: build/Testing/Temporary/LastTest.log
        retention-days: 5
